---
- name: "root : create folders"
  file:
    path: "{{ item.path }}"
    owner: "root"
    group: "root"
    state: directory
    recurse: "{{ item.recurse }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "/home"
      recurse: false
      mode: "0711"
    - path: "/opt/sitepilot"
      recurse: false
      mode: "0711"
    - path: "/opt/sitepilot/users"
      recurse: false
      mode: "0711"
    - path: "/opt/sitepilot/scripts"
      recurse: false
      mode: "0700"
    - path: "/opt/sitepilot/ansible"
      recurse: false
      mode: "0777"
