#!/bin/bash
BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -t 1 ]; then
    IT='-it'
else
    IT=''
fi

case "$1" in
'install'|'install-test'|'install-dev') echo "Installing Autopilot"
    if [ "$1" == 'install' ]; then
        COMPOSER_PARAMS='--no-dev'
    fi

    if [ ! -z "$2" ]; then
        composer config http-basic.nova.laravel.com $2 $3
    fi

    composer install $COMPOSER_PARAMS
    php artisan key:generate
    php artisan migrate --seed

    echo "DONE!"
    ;;
'update'|'update-test'|'update-dev') echo "Updating Autopilot"
    if [ "$1" == 'update' ]; then
        COMPOSER_PARAMS='--no-dev'
    fi

    composer install $COMPOSER_PARAMS
    php artisan migrate --seed

    echo "DONE!"
    ;;
'work') echo "Processing Queue"
    php artisan horizon

    echo "DONE!"
    ;;
*)
    php artisan $@
    ;;
esac