#!/bin/bash
BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -t 1 ]; then
    IT='-it'
else
    IT=''
fi

start() {
    sed -i "s/APP_USER_ID=1000/APP_USER_ID=$(id -u)/" $BASE/.env
    sed -i "s/APP_USER_GID=1000/APP_USER_GID=$(id -g)/" $BASE/.env

    docker-compose -f $BASE/docker-compose.yml --project-directory $BASE up -d --build
}

stop() {
    docker-compose -f $BASE/docker-compose.yml --project-directory $BASE down
}

restart() {
    init
    docker-compose -f $BASE/docker-compose.yml --project-directory $BASE restart
}

pull() {
    docker-compose -f $BASE/docker-compose.yml --project-directory $BASE pull
}

case "$1" in
'start') echo "Starting Autopilot Containers"
    start
    echo "DONE!"
    ;;
'stop') echo "Stopping Autopilot Containers"
    stop
    echo "DONE!"
    ;;
'restart') echo "Restarting Autopilot Containers"
    restart
    echo "DONE!"
    ;;
'install'|'install-test'|'install-dev') echo "Installing Autopilot"
    git pull origin master

    if [ "$1" == 'install' ]; then
        COMPOSER_PARAMS='--no-dev'
    fi

    start

    if [ ! -z "$2" ]; then
        docker exec $IT -w /var/www/html autopilot composer config http-basic.nova.laravel.com $2 $3
    fi

    docker exec $IT -w /var/www/html autopilot composer install $COMPOSER_PARAMS
    docker exec $IT -w /var/www/html autopilot php artisan key:generate
    docker exec $IT -w /var/www/html autopilot php artisan migrate --seed

    echo "DONE!"
    ;;
'update'|'update-test'|'update-dev') echo "Updating Autopilot"
    git pull origin master

    if [ "$1" == 'update' ]; then
        COMPOSER_PARAMS='--no-dev'
    fi
    
    pull
    stop
    start

    docker exec $IT -w /var/www/html autopilot composer install $COMPOSER_PARAMS
    docker exec $IT -w /var/www/html autopilot php artisan migrate --seed

    echo "DONE!"
    ;;
'exec')
    docker exec $IT -w /var/www/html autopilot "${@:2}"
    ;;
*)
    docker exec $IT -w /var/www/html autopilot php artisan $@
    ;;
esac