version: "3.3"

services:
  test-web:
    build: sitepilot/autopilot-test:20.04
    container_name: autopilot-test
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

  test-lb:
    build: sitepilot/autopilot-test:20.04
    container_name: autopilot-test-lb
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
