FROM grafana/grafana:latest
MAINTAINER Sitepilot <support@sitepilot.io>

LABEL org.label-schema.vendor="Sitepilot" \
    org.label-schema.name="autopilot-grafana" \
    org.label-schema.description="Docker image which is used for monitoring Autopilot servers and sites." \
    org.label-schema.url="https://github.com/sitepilot/autopilot"

EXPOSE 3000

VOLUME ["/var/lib/grafana"]
