groups:
  - name: Prometheus
    rules:
      - alert: PrometheusTargetMissing
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.name }}: is down"
          description: "Could not communicate with `{{ $labels.name }}`, please check the connection and `node_exporter` service."
