---
- name: "health : create folders"
  file:
    path: "{{ item }}"
    owner: "{{ admin }}"
    group: "{{ admin }}"
    state: directory
    mode: "0700"
  loop:
    - /opt/sitepilot/services/health
    - /opt/sitepilot/services/health/public

- name: "health : generate health check script"
  template:
    src: health_check.php.j2
    dest: /opt/sitepilot/services/health/public/index.php
