route:
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 30m
  receiver: "slack"
  routes:
    - receiver: "slack"
      group_wait: 10s
      match_re:
        severity: critical|warning
      continue: true

receivers:
  - name: "slack"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/xxxx/xxxx/xxxx"
        send_resolved: true
        channel: "autopilot-test"
        title: "Autopilot Monitor"
        text: "{{ range .Alerts }}[{{ .Status | toUpper }}] {{ .Annotations.summary }}\n{{ .Annotations.description }}\n\n{{ end }}"
