FROM prom/blackbox-exporter:master
MAINTAINER Sitepilot <support@sitepilot.io>

LABEL org.label-schema.vendor="Sitepilot" \
    org.label-schema.name="autopilot-blackbox" \
    org.label-schema.description="Docker image which is used for monitoring Autopilot servers and sites." \
    org.label-schema.url="https://github.com/sitepilot/autopilot"

EXPOSE 9115

COPY tags /
