---
- name: "install : define packages"
  set_fact:
    packages:
      - software-properties-common
      - ca-certificates
      - build-essential
      - curl
      - python3
      - python3-pip
      - python3-setuptools
      - unattended-upgrades
      - zip
      - unzip
      - zsh
      - ncdu
      - gnupg
      - cron
      - nano
      - mysql-client

- name: "install : install required packages"
  apt:
    name: "{{ packages|join(', ') }}"
    state: present
