<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\Text;
use App\Nova\Actions\JobAction;
use Laravel\Nova\Fields\HasMany;
use Laravel\Nova\Fields\Textarea;
use App\Nova\Actions\BackupAction;
use Laravel\Nova\Fields\BelongsTo;

class Database extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Database::class;

    /**
     * Indicates if the resource should be displayed in the sidebar.
     *
     * @var bool
     */
    public static $displayInNavigation = false;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'name';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id', 'name', 'user'
    ];

    /**
     * Get the search result subtitle for the resource.
     *
     * @return string
     */
    public function subtitle()
    {
        return $this->sysuser->name;
    }

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            BelongsTo::make('System User', 'sysuser', Sysuser::class)
                ->searchable()
                ->withoutTrashed()
                ->exceptOnForms(),

            BelongsTo::make('Site', 'site', Site::class)
                ->searchable()
                ->withoutTrashed()
                ->hideWhenUpdating()
                ->help('Database name and user will be generated by Autopilot.'),

            Text::make('Name')
                ->exceptOnForms(),

            Text::make('User')
                ->exceptOnForms(),

            Textarea::make('Password')
                ->hideFromIndex()
                ->hideWhenCreating()
                ->rows(1)
                ->rules(\App\Database::$validationRules['password']),

            \App\Database::getNovaStatusField($this),

            HasMany::make('Backups', 'backups', Backup::class),
            HasMany::make('Tasks', 'tasks', Task::class)
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [
            (new BackupAction)
                ->exceptOnIndex()
                ->showOnTableRow()
                ->canRunWhenReady($this)
                ->setName('Backup Database')
                ->confirmText('Are you sure you want to backup the selected database?')
                ->confirmButtonText('Backup'),
            (new JobAction)
                ->exceptOnIndex()
                ->showOnTableRow()
                ->setName('Provision Database')
                ->setResourceName('database')
                ->setFunctionName('provision')
                ->confirmButtonText('Provision')
                ->confirmText('Are you sure you want to provision the selected database(s)?')
                ->setSuccessMessage('Autopilot will provision your {{resourceName}} in a few seconds.')
                ->canRunWhenNotBusy($this),
        ];
    }
}
