{
 "title": "Servers",
 "tags": [ "Autopilot Monitor" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{instance=~\"$node\"} / node_memory_SwapTotal_bytes{instance=~\"$node\"})) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "Disk Space Used (EXT4/XFS)",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "IOwait",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_15m"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_Avaliable"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "graph",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "s", "label": "Time. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[30m]) / irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Read time"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[30m]) / irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Write time"
    }
   ]
  }
 ]
}