---
name: build-autopilot

on:
  push:
    paths-ignore:
      - "docker/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    services:
      mysql:
        image: mariadb:10.4
        env:
          MYSQL_USER: autopilot
          MYSQL_DATABASE: autopilot
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: supersecret
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      APP_ENV: testing
      APP_KEY: base64:V78KNl8AZXSQ3p7Kapd8Gr/i7D1hJHbB72vsXSVuG1I=
      DB_PORT: 3307

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('composer.json') }}

      - name: Install pip packages
        run: sudo pip install ansible-lint && sudo pip install yamllint

      - name: Run Yaml lint on ansible folder
        run: sudo yamllint -c tests/yamllint.yml ansible/

      - name: Run Ansible lint on ansible folder
        run: sudo ansible-lint -v --force-color ansible/

      - name: Install dependencies
        run: |
          composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}
          composer install --prefer-dist --no-interaction --no-suggest
          php artisan migrate --seed

      - name: Execute tests
        run: |
          php artisan test

      - name: "Failure: dump tasks"
        if: failure()
        run: |
          ./autopilot task:debug

      - name: "Failure: dump logs"
        if: failure()
        run: |
          cat storage/logs/laravel.log
